# Server Port
server:
  port: 8082

# Spring Application Name
spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bookvexedb_j2e
    username: postgres
    password: ""

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  # Previously used: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true

  # Exclude auto-configuration for JDBC DataSource
  # autoconfigure:
  #   exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            type:
              mapping: >
                org.example.bookvexebej2e.models.dto.kafka.NotificationKafkaDTO:com.bookvexe.notificationservice.dto.NotificationKafkaDTO,
                com.example.bookvexe_payment_service.models.dto.kafka.NotificationKafkaDTO:com.bookvexe.notificationservice.dto.NotificationKafkaDTO
